replicaCount: 1

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: artemis-dev.wakulovszki.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
    - secretName: artemis-dev-tls
      hosts:
        - artemis-dev.wakulovszki.com
